service: "split-human-name"
provider:
  name: google
  runtime: nodejs12
  region: us-central1
  project: demos-220218
  credentials: ~/.gcloud/demos.json
plugins:
  - serverless-google-cloudfunctions
package:
  patterns:
    - index.js
functions:
  demo:
    handler: "split-human-name"
    events:
      - http: path
