service: "split-human-name"
provider:
  name: google
  runtime: nodejs8
  region: us-central1
  project: demos-220218
  credentials: ~/.gcloud/demos.json
plugins:
  - serverless-google-cloudfunctions
package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
functions:
  demo:
    handler: "split-human-name"
    events:
      - http: path
